[build]
command = "npm install && npm run railway:build"

[deploy]
command = "npm run railway:start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
