import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 시드 데이터 생성 시작...')

  // 1. 인스타그램 서비스들
  const instagramProducts = [
    {
      platform: 'instagram',
      category: 'followers',
      name: '인스타 실제 한국 팔로워',
      description: '100% 실제 활동하는 한국인 유저들이 인스타 공식앱을 통해 직접 방문하여 팔로우를 눌러드리는 방식으로 안전하게 진행됩니다.',
      price: 1.8, // 개당 가격 (180원 / 100개 = 1.8원)
      originalPrice: 2.0,
      discount: 10,
      minOrder: 20,
      maxOrder: 3000000,
      deliveryTime: '1~6시간',
      quality: 'premium' as const,
      isActive: true,
      isPopular: true,
      isRecommended: true,
      totalOrders: 1250,
      totalRevenue: 2250000,
      features: ['실제 한국인', '30일 AS', '안전한 방식', '프리미엄 품질'],
      icon: '📷',
      unit: '개',
    },
    {
      platform: 'instagram',
      category: 'likes',
      name: '인스타 좋아요',
      description: '인스타그램 게시물의 좋아요를 자연스럽게 증가시켜드립니다.',
      price: 0.15, // 개당 가격 (15원 / 100개 = 0.15원)
      originalPrice: 0.20,
      discount: 25,
      minOrder: 10,
      maxOrder: 50000,
      deliveryTime: '1~30분',
      quality: 'premium' as const,
      isActive: true,
      isPopular: true,
      isRecommended: true,
      totalOrders: 890,
      totalRevenue: 1335000,
      features: ['빠른 시작', '30일 AS', '안전한 방식', '자연스러운 증가'],
      icon: '❤️',
      unit: '개',
    },
    {
      platform: 'instagram',
      category: 'views',
      name: '인스타 조회수',
      description: '인스타그램 게시물의 조회수를 늘려드립니다.',
      price: 0.05,
      minOrder: 100,
      maxOrder: 1000000,
      deliveryTime: '1~12시간',
      quality: 'standard' as const,
      isActive: true,
      isPopular: false,
      isRecommended: false,
      totalOrders: 450,
      totalRevenue: 675000,
      features: ['빠른 처리', '안전한 방식'],
      icon: '👁️',
      unit: '회',
    },
    {
      platform: 'instagram',
      category: 'reels_views',
      name: '인스타 릴스 조회수',
      description: '인스타그램 릴스의 조회수를 늘려드립니다.',
      price: 0.08,
      minOrder: 50,
      maxOrder: 500000,
      deliveryTime: '1~24시간',
      quality: 'premium' as const,
      isActive: true,
      isPopular: true,
      isRecommended: false,
      totalOrders: 320,
      totalRevenue: 480000,
      features: ['실제 조회', '빠른 처리', '안전한 방식'],
      icon: '🎬',
      unit: '회',
    },
    {
      platform: 'instagram',
      category: 'story_views',
      name: '인스타 스토리 조회수',
      description: '인스타그램 스토리의 조회수를 늘려드립니다.',
      price: 0.12,
      minOrder: 20,
      maxOrder: 100000,
      deliveryTime: '1~6시간',
      quality: 'standard' as const,
      isActive: true,
      isPopular: false,
      isRecommended: false,
      totalOrders: 180,
      totalRevenue: 270000,
      features: ['빠른 처리', '24시간 유지'],
      icon: '📖',
      unit: '회',
    }
  ]

  // 2. 유튜브 서비스들
  const youtubeProducts = [
    {
      platform: 'youtube',
      category: 'subscribers',
      name: '유튜브 구독자',
      description: '유튜브 채널의 구독자를 늘려드립니다.',
      price: 0.25, // 개당 가격
      originalPrice: 0.30,
      discount: 16,
      minOrder: 10,
      maxOrder: 100000,
      deliveryTime: '1~24시간',
      quality: 'premium' as const,
      isActive: true,
      isPopular: true,
      isRecommended: true,
      totalOrders: 567,
      totalRevenue: 1417500,
      features: ['실제 유저', '안전한 방식', '빠른 시작', '고품질'],
      icon: '🎥',
      unit: '명',
    },
    {
      platform: 'youtube',
      category: 'views',
      name: '유튜브 조회수',
      description: '유튜브 영상의 조회수를 늘려드립니다.',
      price: 0.03,
      minOrder: 100,
      maxOrder: 1000000,
      deliveryTime: '1~48시간',
      quality: 'standard' as const,
      isActive: true,
      isPopular: true,
      isRecommended: false,
      totalOrders: 890,
      totalRevenue: 890000,
      features: ['점진적 증가', '안전한 방식', '실제 조회'],
      icon: '👀',
      unit: '회',
    },
    {
      platform: 'youtube',
      category: 'likes',
      name: '유튜브 좋아요',
      description: '유튜브 영상의 좋아요를 늘려드립니다.',
      price: 0.8,
      minOrder: 10,
      maxOrder: 50000,
      deliveryTime: '1~24시간',
      quality: 'premium' as const,
      isActive: true,
      isPopular: false,
      isRecommended: true,
      totalOrders: 234,
      totalRevenue: 468000,
      features: ['실제 유저', '안전한 방식', '고품질'],
      icon: '👍',
      unit: '개',
    }
  ]

  // 3. 페이스북 서비스들
  const facebookProducts = [
    {
      platform: 'facebook',
      category: 'likes',
      name: '페이스북 좋아요',
      description: '페이스북 게시물의 좋아요를 늘려드립니다.',
      price: 0.20,
      minOrder: 10,
      maxOrder: 10000,
      deliveryTime: '1~24시간',
      quality: 'standard' as const,
      isActive: true,
      isPopular: false,
      isRecommended: false,
      totalOrders: 123,
      totalRevenue: 246000,
      features: ['실제 유저', '안전한 방식'],
      icon: '👍',
      unit: '개',
    },
    {
      platform: 'facebook',
      category: 'page_likes',
      name: '페이스북 페이지 좋아요',
      description: '페이스북 페이지의 좋아요를 늘려드립니다.',
      price: 0.50,
      minOrder: 10,
      maxOrder: 50000,
      deliveryTime: '1~48시간',
      quality: 'premium' as const,
      isActive: true,
      isPopular: false,
      isRecommended: false,
      totalOrders: 78,
      totalRevenue: 195000,
      features: ['실제 유저', '안전한 방식', '고품질'],
      icon: '📘',
      unit: '개',
    }
  ]

  // 4. 틱톡 서비스들
  const tiktokProducts = [
    {
      platform: 'tiktok',
      category: 'followers',
      name: '틱톡 팔로워',
      description: '틱톡 계정의 팔로워를 늘려드립니다.',
      price: 0.30,
      originalPrice: 0.35,
      discount: 14,
      minOrder: 20,
      maxOrder: 50000,
      deliveryTime: '1~24시간',
      quality: 'premium' as const,
      isActive: true,
      isPopular: false,
      isRecommended: true,
      totalOrders: 234,
      totalRevenue: 702000,
      features: ['실제 유저', '안전한 방식', '고품질', '빠른 시작'],
      icon: '🎵',
      unit: '명',
    },
    {
      platform: 'tiktok',
      category: 'likes',
      name: '틱톡 좋아요',
      description: '틱톡 영상의 좋아요를 늘려드립니다.',
      price: 0.10,
      minOrder: 10,
      maxOrder: 100000,
      deliveryTime: '1~12시간',
      quality: 'standard' as const,
      isActive: true,
      isPopular: true,
      isRecommended: false,
      totalOrders: 456,
      totalRevenue: 456000,
      features: ['빠른 처리', '안전한 방식'],
      icon: '❤️',
      unit: '개',
    },
    {
      platform: 'tiktok',
      category: 'views',
      name: '틱톡 조회수',
      description: '틱톡 영상의 조회수를 늘려드립니다.',
      price: 0.02,
      minOrder: 100,
      maxOrder: 1000000,
      deliveryTime: '1~24시간',
      quality: 'standard' as const,
      isActive: true,
      isPopular: true,
      isRecommended: false,
      totalOrders: 789,
      totalRevenue: 789000,
      features: ['점진적 증가', '안전한 방식', '대량 주문 가능'],
      icon: '👁️',
      unit: '회',
    }
  ]

  // 5. 트위터 서비스들
  const twitterProducts = [
    {
      platform: 'twitter',
      category: 'followers',
      name: '트위터 팔로워',
      description: '트위터 계정의 팔로워를 늘려드립니다.',
      price: 0.35,
      minOrder: 10,
      maxOrder: 50000,
      deliveryTime: '1~24시간',
      quality: 'standard' as const,
      isActive: true,
      isPopular: false,
      isRecommended: false,
      totalOrders: 123,
      totalRevenue: 430500,
      features: ['실제 유저', '안전한 방식', '빠른 시작'],
      icon: '🐦',
      unit: '명',
    },
    {
      platform: 'twitter',
      category: 'likes',
      name: '트위터 좋아요',
      description: '트위터 트윗의 좋아요를 늘려드립니다.',
      price: 0.25,
      minOrder: 10,
      maxOrder: 10000,
      deliveryTime: '1~12시간',
      quality: 'standard' as const,
      isActive: true,
      isPopular: false,
      isRecommended: false,
      totalOrders: 89,
      totalRevenue: 222500,
      features: ['빠른 처리', '안전한 방식'],
      icon: '❤️',
      unit: '개',
    },
    {
      platform: 'twitter',
      category: 'retweets',
      name: '트위터 리트윗',
      description: '트위터 트윗의 리트윗을 늘려드립니다.',
      price: 1.5,
      minOrder: 5,
      maxOrder: 5000,
      deliveryTime: '1~24시간',
      quality: 'premium' as const,
      isActive: true,
      isPopular: false,
      isRecommended: false,
      totalOrders: 45,
      totalRevenue: 337500,
      features: ['실제 유저', '안전한 방식', '고품질'],
      icon: '🔄',
      unit: '개',
    }
  ]

  // 6. 비활성화된 플랫폼 서비스들 (개발 예정) - 이미지의 모든 플랫폼 포함
  const inactiveProducts = [
    // 추천서비스
    {
      platform: 'recommended',
      category: 'special',
      name: '추천 서비스 패키지',
      description: '가장 인기있는 서비스들을 조합한 특별 패키지입니다. (개발 예정)',
      price: 0.50,
      minOrder: 10,
      maxOrder: 10000,
      deliveryTime: '개발 예정',
      quality: 'premium' as const,
      isActive: false,
      isPopular: false,
      isRecommended: false,
      totalOrders: 0,
      totalRevenue: 0,
      features: ['개발 예정'],
      icon: '⭐',
      unit: '패키지',
    },
    // 이벤트
    {
      platform: 'event',
      category: 'special',
      name: '이벤트 서비스',
      description: '특별 이벤트 및 프로모션 서비스입니다. (개발 예정)',
      price: 0.30,
      minOrder: 10,
      maxOrder: 10000,
      deliveryTime: '개발 예정',
      quality: 'standard' as const,
      isActive: false,
      isPopular: false,
      isRecommended: false,
      totalOrders: 0,
      totalRevenue: 0,
      features: ['개발 예정'],
      icon: '🎁',
      unit: '개',
    },
    // 상위노출
    {
      platform: 'seo',
      category: 'ranking',
      name: '상위노출 서비스',
      description: '검색 결과 상위노출을 위한 SEO 서비스입니다. (개발 예정)',
      price: 5.0,
      minOrder: 1,
      maxOrder: 100,
      deliveryTime: '개발 예정',
      quality: 'premium' as const,
      isActive: false,
      isPopular: false,
      isRecommended: false,
      totalOrders: 0,
      totalRevenue: 0,
      features: ['개발 예정'],
      icon: '📊',
      unit: '회',
    },
    // 계정관리
    {
      platform: 'management',
      category: 'service',
      name: '계정 관리 서비스',
      description: 'SNS 계정 전문 관리 서비스입니다. (개발 예정)',
      price: 10.0,
      minOrder: 1,
      maxOrder: 10,
      deliveryTime: '개발 예정',
      quality: 'premium' as const,
      isActive: false,
      isPopular: false,
      isRecommended: false,
      totalOrders: 0,
      totalRevenue: 0,
      features: ['개발 예정'],
      icon: '⚙️',
      unit: '월',
    },
    // 패키지
    {
      platform: 'package',
      category: 'bundle',
      name: '패키지 서비스',
      description: '여러 서비스를 조합한 할인 패키지입니다. (개발 예정)',
      price: 2.0,
      minOrder: 1,
      maxOrder: 100,
      deliveryTime: '개발 예정',
      quality: 'premium' as const,
      isActive: false,
      isPopular: false,
      isRecommended: false,
      totalOrders: 0,
      totalRevenue: 0,
      features: ['개발 예정'],
      icon: '📦',
      unit: '패키지',
    },
    // 스레드
    {
      platform: 'threads',
      category: 'followers',
      name: '스레드 팔로워',
      description: '스레드 계정의 팔로워를 늘려드립니다. (개발 예정)',
      price: 0.40,
      minOrder: 10,
      maxOrder: 10000,
      deliveryTime: '개발 예정',
      quality: 'standard' as const,
      isActive: false,
      isPopular: false,
      isRecommended: false,
      totalOrders: 0,
      totalRevenue: 0,
      features: ['개발 예정'],
      icon: '🔗',
      unit: '명',
    },
    // Nz로블
    {
      platform: 'nzroble',
      category: 'special',
      name: 'Nz로블 서비스',
      description: 'Nz로블 플랫폼 전용 서비스입니다. (개발 예정)',
      price: 0.50,
      minOrder: 10,
      maxOrder: 10000,
      deliveryTime: '개발 예정',
      quality: 'standard' as const,
      isActive: false,
      isPopular: false,
      isRecommended: false,
      totalOrders: 0,
      totalRevenue: 0,
      features: ['개발 예정'],
      icon: '📌',
      unit: '개',
    },
    // 뉴스언론보도
    {
      platform: 'news',
      category: 'media',
      name: '뉴스 언론보도 서비스',
      description: '뉴스 및 언론 매체를 통한 홍보 서비스입니다. (개발 예정)',
      price: 100.0,
      minOrder: 1,
      maxOrder: 10,
      deliveryTime: '개발 예정',
      quality: 'premium' as const,
      isActive: false,
      isPopular: false,
      isRecommended: false,
      totalOrders: 0,
      totalRevenue: 0,
      features: ['개발 예정'],
      icon: '📈',
      unit: '건',
    },
    // 채널단
    {
      platform: 'channel',
      category: 'management',
      name: '채널단 서비스',
      description: '채널 전문 관리 서비스입니다. (개발 예정)',
      price: 20.0,
      minOrder: 1,
      maxOrder: 10,
      deliveryTime: '개발 예정',
      quality: 'premium' as const,
      isActive: false,
      isPopular: false,
      isRecommended: false,
      totalOrders: 0,
      totalRevenue: 0,
      features: ['개발 예정'],
      icon: '🎬',
      unit: '개',
    },
    // 카카오
    {
      platform: 'kakao',
      category: 'views',
      name: '카카오 조회수',
      description: '카카오 콘텐츠의 조회수를 늘려드립니다. (개발 예정)',
      price: 0.10,
      minOrder: 10,
      maxOrder: 10000,
      deliveryTime: '개발 예정',
      quality: 'standard' as const,
      isActive: false,
      isPopular: false,
      isRecommended: false,
      totalOrders: 0,
      totalRevenue: 0,
      features: ['개발 예정'],
      icon: '📺',
      unit: '회',
    },
    // 스토어마케팅
    {
      platform: 'store',
      category: 'marketing',
      name: '스토어 마케팅',
      description: '온라인 스토어 전문 마케팅 서비스입니다. (개발 예정)',
      price: 50.0,
      minOrder: 1,
      maxOrder: 10,
      deliveryTime: '개발 예정',
      quality: 'premium' as const,
      isActive: false,
      isPopular: false,
      isRecommended: false,
      totalOrders: 0,
      totalRevenue: 0,
      features: ['개발 예정'],
      icon: '🎭',
      unit: '개',
    },
    // 어플마케팅
    {
      platform: 'app',
      category: 'marketing',
      name: '어플 마케팅',
      description: '모바일 앱 전문 마케팅 서비스입니다. (개발 예정)',
      price: 30.0,
      minOrder: 1,
      maxOrder: 10,
      deliveryTime: '개발 예정',
      quality: 'premium' as const,
      isActive: false,
      isPopular: false,
      isRecommended: false,
      totalOrders: 0,
      totalRevenue: 0,
      features: ['개발 예정'],
      icon: '🎯',
      unit: '개',
    },
    // SEO트래픽
    {
      platform: 'seo_traffic',
      category: 'traffic',
      name: 'SEO 트래픽',
      description: 'SEO 최적화를 통한 웹사이트 트래픽 증가 서비스입니다. (개발 예정)',
      price: 2.0,
      minOrder: 100,
      maxOrder: 100000,
      deliveryTime: '개발 예정',
      quality: 'premium' as const,
      isActive: false,
      isPopular: false,
      isRecommended: false,
      totalOrders: 0,
      totalRevenue: 0,
      features: ['개발 예정'],
      icon: '⚙️',
      unit: '방문자',
    },
    // 기타
    {
      platform: 'other',
      category: 'misc',
      name: '기타 서비스',
      description: '기타 특수 요청 서비스입니다. (개발 예정)',
      price: 10.0,
      minOrder: 1,
      maxOrder: 100,
      deliveryTime: '개발 예정',
      quality: 'standard' as const,
      isActive: false,
      isPopular: false,
      isRecommended: false,
      totalOrders: 0,
      totalRevenue: 0,
      features: ['개발 예정'],
      icon: '🔧',
      unit: '건',
    },
    // 네이버 서비스들
    {
      platform: 'naver',
      category: 'views',
      name: '네이버 블로그 조회수',
      description: '네이버 블로그 조회수를 늘려드립니다. (개발 예정)',
      price: 0.05,
      minOrder: 100,
      maxOrder: 100000,
      deliveryTime: '개발 예정',
      quality: 'standard' as const,
      isActive: false,
      isPopular: false,
      isRecommended: false,
      totalOrders: 0,
      totalRevenue: 0,
      features: ['개발 예정'],
      icon: '📝',
      unit: '회',
    },
    {
      platform: 'naver',
      category: 'likes',
      name: '네이버 카페 좋아요',
      description: '네이버 카페 게시물 좋아요를 늘려드립니다. (개발 예정)',
      price: 0.30,
      minOrder: 10,
      maxOrder: 10000,
      deliveryTime: '개발 예정',
      quality: 'standard' as const,
      isActive: false,
      isPopular: false,
      isRecommended: false,
      totalOrders: 0,
      totalRevenue: 0,
      features: ['개발 예정'],
      icon: '☕',
      unit: '개',
    }
  ]

  // 모든 제품 배열 합치기
  const allProducts = [
    ...instagramProducts,
    ...youtubeProducts,
    ...facebookProducts,
    ...tiktokProducts,
    ...twitterProducts,
    ...inactiveProducts
  ]

  // 기존 제품 삭제 (개발용)
  await prisma.product.deleteMany({})
  console.log('🗑️ 기존 제품 데이터 삭제 완료')

  // 새로운 제품 생성
  for (const product of allProducts) {
    await prisma.product.create({
      data: {
        ...product,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    })
  }

  console.log(`✅ ${allProducts.length}개의 제품 생성 완료`)
  console.log('📊 생성된 제품 통계:')
  console.log(`  - 인스타그램: ${instagramProducts.length}개`)
  console.log(`  - 유튜브: ${youtubeProducts.length}개`)
  console.log(`  - 페이스북: ${facebookProducts.length}개`)
  console.log(`  - 틱톡: ${tiktokProducts.length}개`)
  console.log(`  - 트위터: ${twitterProducts.length}개`)
  console.log(`  - 비활성화: ${inactiveProducts.length}개`)
}

main()
  .catch((e) => {
    console.error('❌ 시드 데이터 생성 실패:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
